/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import gui.Login;
import gui.Register;
import javax.swing.JPanel;
import java.awt.Color;
import java.awt.event.*;

/**
 *
 * @author hieud
 */
public class Application extends javax.swing.JFrame implements ActionListener {
    private JPanel registerPanel;
//    private JPanel loginForm = new Login();
    /**
     * Creates new form application
     */
    public Application() {
        initComponents();
        this.setVisible(true);
    }
    
    public void removeAndUpdate() {
    	this.getContentPane().removeAll();
    	this.invalidate();
    	this.validate();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogin = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        loginPanel = new gui.Login();
        registerPanel = new gui.Register();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(39, 79, 199));
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Đăng nhập");
        btnLogin.setBorder(null);
        btnLogin.setOpaque(false);

        btnRegister.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("Tạo tài khoản");
        btnRegister.setBorder(null);
        btnRegister.setOpaque(false);
     
        getContentPane().add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 530, -1, -1));
        getContentPane().add(loginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        btnLogin.addActionListener(this);
        btnRegister.addActionListener(this);
        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private gui.Login loginPanel;
    // End of variables declaration//GEN-END:variables
	@Override
	public void actionPerformed(ActionEvent e) {
        Object obj = e.getSource();
        if(obj.equals(this.btnRegister))
        {
            System.out.print("register button works");
            this.removeAndUpdate();
//            this.getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 650, -1, -1));
//            this.getContentPane().add(registerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
//            
//            this.getContentPane().validate();
        }
        else if(obj.equals(this.btnLogin))
        {
            System.out.print("login button works");
            this.getContentPane().remove(this.registerPanel);
            this.removeAndUpdate();
            this.getContentPane().add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 530, -1, -1));
            this.getContentPane().add(loginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
            this.validate();
	    }

	}
}
