/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

/**
 *
 * @author hieud
 */
public class GUI_Menu extends javax.swing.JPanel {

    /**
     * Creates new form menu
     */
    public GUI_Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAo = new javax.swing.JButton();
        btnDonHang = new javax.swing.JButton();
        btnNV = new javax.swing.JButton();
        btnKH = new javax.swing.JButton();
        iconKH = new javax.swing.JLabel();
        iconAo = new javax.swing.JLabel();
        iconNV = new javax.swing.JLabel();
        iconDonHang = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        rightTab = new javax.swing.JLabel();
        mainMenu = new javax.swing.JTabbedPane();
        quanAoPanel1 = new gui.GUI_QuanAoPanel();

        setPreferredSize(new java.awt.Dimension(1280, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAo.setForeground(new java.awt.Color(255, 255, 255));
        btnAo.setText("QUẦN ÁO");
        btnAo.setBorder(null);
        btnAo.setBorderPainted(false);
        btnAo.setContentAreaFilled(false);
        add(btnAo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, 40));

        btnDonHang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDonHang.setForeground(new java.awt.Color(255, 255, 255));
        btnDonHang.setText("ĐƠN HÀNG");
        btnDonHang.setBorder(null);
        btnDonHang.setBorderPainted(false);
        btnDonHang.setContentAreaFilled(false);
        add(btnDonHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, 40));

        btnNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNV.setForeground(new java.awt.Color(255, 255, 255));
        btnNV.setText("NHÂN VIÊN");
        btnNV.setBorder(null);
        btnNV.setBorderPainted(false);
        btnNV.setContentAreaFilled(false);
        add(btnNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, -1, 30));

        btnKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnKH.setForeground(new java.awt.Color(255, 255, 255));
        btnKH.setText("KHÁCH HÀNG");
        btnKH.setBorder(null);
        btnKH.setBorderPainted(false);
        btnKH.setContentAreaFilled(false);
        btnKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKHActionPerformed(evt);
            }
        });
        add(btnKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, -1, 30));

        iconKH.setIcon(new javax.swing.ImageIcon("C:\\Users\\hieud\\Documents\\NetBeansProjects\\ShopQuanAo\\resources\\iconNv.png")); // NOI18N
        add(iconKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 20, -1));

        iconAo.setIcon(new javax.swing.ImageIcon("C:\\Users\\hieud\\Documents\\NetBeansProjects\\ShopQuanAo\\resources\\iconAo.png")); // NOI18N
        add(iconAo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 20, -1));

        iconNV.setIcon(new javax.swing.ImageIcon("C:\\Users\\hieud\\Documents\\NetBeansProjects\\ShopQuanAo\\resources\\iconNv.png")); // NOI18N
        add(iconNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 20, -1));

        iconDonHang.setIcon(new javax.swing.ImageIcon("C:\\Users\\hieud\\Documents\\NetBeansProjects\\ShopQuanAo\\resources\\iconDonHang.png")); // NOI18N
        add(iconDonHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        logo.setIcon(new javax.swing.ImageIcon("C:\\Users\\hieud\\Documents\\NetBeansProjects\\ShopQuanAo\\resources\\shopQuanAo.png")); // NOI18N
        add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        rightTab.setIcon(new javax.swing.ImageIcon("C:\\Users\\hieud\\Documents\\NetBeansProjects\\ShopQuanAo\\resources\\BG.png")); // NOI18N
        rightTab.setFocusable(false);
        rightTab.setPreferredSize(new java.awt.Dimension(250, 720));
        add(rightTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        mainMenu.setBackground(new java.awt.Color(255, 255, 255));
        mainMenu.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        mainMenu.addTab("tabQuanAo", quanAoPanel1);

        add(mainMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, -10, 1140, 750));
    }// </editor-fold>//GEN-END:initComponents

    private void btnKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKHActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAo;
    private javax.swing.JButton btnDonHang;
    private javax.swing.JButton btnKH;
    private javax.swing.JButton btnNV;
    private javax.swing.JLabel iconAo;
    private javax.swing.JLabel iconDonHang;
    private javax.swing.JLabel iconKH;
    private javax.swing.JLabel iconNV;
    private javax.swing.JLabel logo;
    private javax.swing.JTabbedPane mainMenu;
    private gui.GUI_QuanAoPanel quanAoPanel1;
    private javax.swing.JLabel rightTab;
    // End of variables declaration//GEN-END:variables
}
