/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import gui.GUI_Login;
import gui.GUI_Register;
import gui.GUI_Menu;
import javax.swing.JPanel;
import java.awt.Color;
import java.awt.event.*;

/**
 *
 * @author hieud
 */
public class GUI_Application extends javax.swing.JFrame implements ActionListener {
    private JPanel registerPanel;
    private JPanel loginPanel;
    //    private JPanel loginForm = new Login();
    /**
     * Creates new form application
     */
    public GUI_Application() {
        initComponents();
        this.setVisible(true);
    }
    
    public void removeAndUpdate() {
    	this.getContentPane().removeAll();
    	this.revalidate();
    	this.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGuestMode = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        gUI_Menu1 = new gui.GUI_Menu();
        loginPanel = new GUI_Login();
        registerPanel = new GUI_Register();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(39, 79, 199));
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuestMode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGuestMode.setForeground(new java.awt.Color(255, 255, 255));
        btnGuestMode.setText("Quay lại");
        btnGuestMode.setBorderPainted(false);
        btnGuestMode.setContentAreaFilled(false);

        btnLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Đăng nhập");
        btnLogin.setBorder(null);
        btnLogin.setBorderPainted(false);
        btnLogin.setContentAreaFilled(false);
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 640, -1, -1));

        btnRegister.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("Tạo tài khoản");
        btnRegister.setBorder(null);
        btnRegister.setBorderPainted(false);
        btnRegister.setContentAreaFilled(false);
        getContentPane().add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 680, -1, -1));
        getContentPane().add(gUI_Menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        this.btnLogin.addActionListener(this);
        this.btnRegister.addActionListener(this);
        this.btnGuestMode.addActionListener(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuestMode;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private gui.GUI_Menu gUI_Menu1;
    // End of variables declaration//GEN-END:variables
	@Override
	public void actionPerformed(ActionEvent e) {
        Object obj = e.getSource();
        if(obj.equals(this.btnRegister))
        {
            this.removeAndUpdate();
            this.getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 650, -1, -1));
            this.getContentPane().add(btnGuestMode, new org.netbeans.lib.awtextra.AbsoluteConstraints(579, 670, 130, -1));
            this.getContentPane().add(registerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
            this.revalidate();
        	this.repaint();
        }
        else if(obj.equals(this.btnLogin))
        {
            this.removeAndUpdate();
            this.getContentPane().add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 530, -1, -1));
            this.getContentPane().add(btnGuestMode, new org.netbeans.lib.awtextra.AbsoluteConstraints(579, 570, 130, -1));
            this.getContentPane().add(loginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
            this.revalidate();
        	this.repaint();
	    }
        else if(obj.equals(this.btnGuestMode))
        {
        	this.removeAndUpdate();
        	this.getContentPane().add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 680, -1, -1));
        	this.getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 640, -1, -1));
            this.getContentPane().add(gUI_Menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
            this.revalidate();
            this.repaint();
        }
        
    }
}
