/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

/**
 *
 * @author hieud
 */
public class GUI_QuanAoPanel extends javax.swing.JPanel {

    /**
     * Creates new form quanAoPanel
     */
    public GUI_QuanAoPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTimKiem = new javax.swing.JTextField();
        searchBox = new javax.swing.JLabel();
        btnTimKiem = new javax.swing.JButton();
        quanAoUI1 = new gui.QuanAoUI();
        quanAoUI2 = new gui.QuanAoUI();
        quanAoUI3 = new gui.QuanAoUI();
        quanAoUI4 = new gui.QuanAoUI();
        quanAoUI5 = new gui.QuanAoUI();
        quanAoUI6 = new gui.QuanAoUI();
        quanAoUI7 = new gui.QuanAoUI();
        quanAoUI8 = new gui.QuanAoUI();
        quanAoUI9 = new gui.QuanAoUI();
        quanAoUI10 = new gui.QuanAoUI();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1100, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTimKiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTimKiem.setText("Tìm kiếm");
        txtTimKiem.setBorder(null);
        txtTimKiem.setOpaque(false);
        add(txtTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 260, 50));

        searchBox.setIcon(new javax.swing.ImageIcon("C:\\Users\\hieud\\Documents\\NetBeansProjects\\ShopQuanAo\\resources\\search.png")); // NOI18N
        add(searchBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        btnTimKiem.setBackground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        add(btnTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 86, 45));

        quanAoUI1.setPreferredSize(new java.awt.Dimension(151, 200));
        add(quanAoUI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 159, 235));

        quanAoUI2.setPreferredSize(new java.awt.Dimension(151, 200));
        add(quanAoUI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 159, 235));

        quanAoUI3.setPreferredSize(new java.awt.Dimension(151, 200));
        add(quanAoUI3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 159, 235));

        quanAoUI4.setPreferredSize(new java.awt.Dimension(151, 200));
        add(quanAoUI4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 159, 235));

        quanAoUI5.setPreferredSize(new java.awt.Dimension(151, 200));
        add(quanAoUI5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 159, 235));

        quanAoUI6.setPreferredSize(new java.awt.Dimension(151, 200));
        add(quanAoUI6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 159, 235));

        quanAoUI7.setPreferredSize(new java.awt.Dimension(151, 200));
        add(quanAoUI7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, 159, 235));

        quanAoUI8.setPreferredSize(new java.awt.Dimension(151, 200));
        add(quanAoUI8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, 159, 235));

        quanAoUI9.setPreferredSize(new java.awt.Dimension(151, 200));
        add(quanAoUI9, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 140, 159, 235));

        quanAoUI10.setPreferredSize(new java.awt.Dimension(151, 200));
        add(quanAoUI10, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 400, 159, 235));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTimKiem;
    private gui.QuanAoUI quanAoUI1;
    private gui.QuanAoUI quanAoUI10;
    private gui.QuanAoUI quanAoUI2;
    private gui.QuanAoUI quanAoUI3;
    private gui.QuanAoUI quanAoUI4;
    private gui.QuanAoUI quanAoUI5;
    private gui.QuanAoUI quanAoUI6;
    private gui.QuanAoUI quanAoUI7;
    private gui.QuanAoUI quanAoUI8;
    private gui.QuanAoUI quanAoUI9;
    private javax.swing.JLabel searchBox;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
