/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

/**
 *
 * @author hieud
 */
public class GUI_QuanAoPanel extends javax.swing.JPanel {

    /**
     * Creates new form quanAoPanel
     */
    public GUI_QuanAoPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTimKiem = new javax.swing.JTextField();
        searchBox = new javax.swing.JLabel();
        btnLuoi = new javax.swing.JButton();
        btnDsQA = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        scrollGrid = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        scrollList = new javax.swing.JScrollPane();
        tableQuanAo = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1100, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTimKiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTimKiem.setText("Tìm kiếm");
        txtTimKiem.setBorder(null);
        txtTimKiem.setOpaque(false);
        add(txtTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 260, 50));

        searchBox.setIcon(new javax.swing.ImageIcon("C:\\Users\\hieud\\Documents\\NetBeansProjects\\ShopQuanAo\\resources\\search.png")); // NOI18N
        add(searchBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        btnLuoi.setBackground(new java.awt.Color(255, 255, 255));
        btnLuoi.setIcon(new javax.swing.ImageIcon("C:\\Users\\hieud\\Documents\\NetBeansProjects\\ShopQuanAo\\resources\\list.png")); // NOI18N
        btnLuoi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnLuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuoiActionPerformed(evt);
            }
        });
        add(btnLuoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 50, 45));

        btnDsQA.setBackground(new java.awt.Color(255, 255, 255));
        btnDsQA.setIcon(new javax.swing.ImageIcon("C:\\Users\\hieud\\Documents\\NetBeansProjects\\ShopQuanAo\\resources\\grid.png")); // NOI18N
        btnDsQA.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        add(btnDsQA, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 50, 45));

        btnTimKiem.setBackground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        add(btnTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 86, 45));

        scrollGrid.setBackground(new java.awt.Color(255, 255, 255));
        scrollGrid.setBorder(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(835, 1000));
        jPanel1.setLayout(new java.awt.GridLayout(4, 5, 40, 20));
        scrollGrid.setViewportView(jPanel1);

        add(scrollGrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 960, 570));

        tableQuanAo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Tên sản phẩm", "Thương hiệu", "Đơn giá", "Tồn"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableQuanAo.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tableQuanAo.setCellSelectionEnabled(true);
        tableQuanAo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tableQuanAo.setRowHeight(30);
        tableQuanAo.setShowGrid(true);
        scrollList.setViewportView(tableQuanAo);

        add(scrollList, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 960, 570));
    }// </editor-fold>//GEN-END:initComponents

    private void btnLuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLuoiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDsQA;
    private javax.swing.JButton btnLuoi;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane scrollGrid;
    private javax.swing.JScrollPane scrollList;
    private javax.swing.JLabel searchBox;
    private javax.swing.JTable tableQuanAo;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
